argv = require('yargs')
  .strict()
  .usage('Sandbox\nUsage: $0 [task, ...] [options]')
  .example('$0 watch', 'watch files for development')
  .example('$0 build -f', 'fail on error and print it to output')
  .example('$0 build -fpi', 'build for deployment with detailed information for CI')
  .example('$0 build -fpll', 'compile code using Google Closure Compiler with ADVANCED_OPTIMIZATIONS')
  .example('$0 clean', 'delete build directory')
  .example('$0 js:build', 'run specific task')
  .boolean('f')
  .alias('f', 'failOnError')
  .describe('f', 'Fail on error in streams')
  .default('f', no)
  .boolean('d')
  .alias('d', 'debug')
  .describe('d', 'Debug closure application with goog.DEBUG')
  .default('d', no)
  .count('i')
  .alias('i', 'info')
  .describe('i', 'Detailed information about running tasks [-i[i]]')
  .count('l')
  .alias('l', 'level')
  .describe('l', 'Compilation level of Google Closure Compiler [-l[l]]')
  .boolean('p')
  .alias('p', 'production')
  .describe('p', 'Compression of files for production')
  .default('p', no)
  .boolean('s')
  .alias('s', 'sourcemaps')
  .describe('s', 'Generate sourcemaps for debugging')
  .default('s', no)
  .alias('h', 'help')
  .help('h')
  .argv

module.exports = argv
